[package]
name = "where"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.5.0"
clap = {version = "4.5.3", features = ["derive"]}
colored = "2.1.0"
regex = "1.10.4"
rayon = "1.10.0"